version: "3"

services:
  app:
    build: .
    command: python main.py
    # volumes:
    #  - ./vote:/app
    ports:
      - 8001:8000
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ~/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
  

  # worker:
  #   build:
  #     context: ./worker
  #   networks:
  #     - back-tier

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports: ["6379"]
  #   networks:
  #     - back-tier

  # db:
  #   image: postgres:9.4
  #   container_name: db
  #   volumes:
  #     - "db-data:/var/lib/postgresql/data"
  #   networks:
  #     - back-tier

volumes:
  db-data:
